# .gitlab-ci.yml

# use the tidyverse rocker image, as it contains devtools preinstalled
image: rocker/tidyverse

# define stages of runner. at the moment,
# just test (no build or deploy).
stages:
  - test
  - build

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

# define test job
test-job:
  stage: test
  script:
    # Install packages
    - R -e 'install.packages(c("devtools", "BiocManager"))'
    - R -e 'BiocManager::install("BiocCheck")'
    # Run R command check
    - R -e 'devtools::check()'
    # BiocCheck
    - R -e 'BiocCheck::BiocCheck()'
  cache:
    paths:
    - $R_LIBS_USER

build-job:
  stage: build
  script:
    # install
    - R -e 'devtools::install()'
  cache:
    paths:
    - $R_LIBS_USER
    